appenders:
  console:
    kind: console
    filters:
      - kind: threshold
        level: info

  rolling_file:
    kind: rolling_file
    path: log/realtps-job-name.log
    encoder:
      kind: pattern
    policy:
      trigger:
        kind: size
        limit: 100 mb
      roller:
        kind: fixed_window
        base: 1
        count: 5
        pattern: log/realtps-job-name.{}.log

root:
  level: warn
  appenders:
    - console
    - rolling_file

loggers:
  realtps_common:
    level: debug
  realtps_import:
    level: debug

  