# These are all public endpoints.
#
# Note that without a fast network, and perhaps a private node, we will not be
# able to keep up with Solana block production.
#
# https://rpc.info/ - Ethereum-type chain endpoints
#
# https://github.com/cosmos/chain-registry - Cosmos chains rpc info

[chains]
arbitrum = "https://arb1.arbitrum.io/rpc"
avalanche = "https://api.avax.network/ext/bc/C/rpc"
binance = "https://bsc-dataseed.binance.org"
celo = "https://forno.celo.org"
# rpc disappeared
# cosmoshub = "https://rpc-cosmoshub.keplr.app"
cronos = "https://evm-cronos.crypto.org"
ethereum = "https://mainnet.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161"
fantom = "https://rpc.ftm.tools"
harmony = "https://api.harmony.one"
heco = "https://http-mainnet-node.huobichain.com"
kucoin = "https://rpc-mainnet.kcc.network"
kusama = "https://kusama-rpc.polkadot.io"
moonriver = "https://rpc.moonriver.moonbeam.network"
near = "https://rpc.mainnet.near.org"
okex = "https://exchainrpc.okex.org"
# banned
# optimism = "https://mainnet.optimism.io"
osmosis = "https://rpc-osmosis.keplr.app"
polkadot = "https://rpc.polkadot.io"
polygon = "https://polygon-rpc.com"
rootstock = "https://public-node.rsk.co"
secretnetwork = "https://rpc-secret.scrtlabs.com/secret-4/rpc/"
# - node version for secretnetwork: 0.34.14 with url https://api.secretapi.io/
# - node version for secretnetwork: QUWKxOSYaI with url https://rpc-secret.scrtlabs.com/secret-4/rpc/
solana = "https://api.mainnet-beta.solana.com"
stellar = "https://horizon.stellar.org"
terra = "http://public-node.terra.dev:26657"
xdai = "https://rpc.xdaichain.com"