# https://rpc.info/

[chains]
arbitrum = "https://arb1.arbitrum.io/rpc"
avalanche = "https://api.avax.network/ext/bc/C/rpc"
binance = "https://bsc-dataseed.binance.org"
celo = "https://forno.celo.org"
cronos = "https://evm-cronos.crypto.org"
ethereum = "https://mainnet.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161"
fantom = "https://rpc.ftm.tools"
fuse = "https://rpc.fuse.io"
harmony = "https://api.harmony.one"
heco = "https://http-mainnet-node.huobichain.com"
kucoin = "https://rpc-mainnet.kcc.network"
moonriver = "https://rpc.moonriver.moonbeam.network"
okex = "https://exchainrpc.okex.org"
polygon = "https://polygon-rpc.com"
rootstock = "https://public-node.rsk.co"
telos = "https://mainnet.telos.net/evm"
xdai = "https://rpc.xdaichain.com"