[package]
name = "realtps_import"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
realtps_common = { path = "../realtps_common" }
anyhow = "1.0.45"
structopt = "0.3.25"
ethers = "0.6.2"
tokio = { version = "1.5", features = ["macros", "rt-multi-thread"] }
