[package]
name = "realtps_import"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
realtps_common = { path = "../realtps_common" }
anyhow = "1.0.51"
structopt = "0.3.25"
ethers = "0.6.2"
tokio = { version = "1.15.0", features = ["macros", "rt-multi-thread", "time"] }
rand = "0.8.4"
serde = { version = "1.0.132", features = ["derive"] }
toml = "0.5.8"
futures = "0.3.19"
log = "0.4.14"
env_logger = "0.9.0"
async-trait = "0.1.52"
solana-client = "1.9.1"
solana-sdk = "1.9.1"
solana-transaction-status = "1.9.1"
near-jsonrpc-client = "0.2.0"
near-primitives = "0.11.0"
near-jsonrpc-primitives = "0.11.0"
tendermint-rpc = { version = "0.23.1", features = ["http-client"] }
tendermint = "0.23.1"
tendermint-proto = "0.23.1"

substrate-api-client = "0.6.6"
sp-core = "3"
sp-runtime = "3"
