[package]
name = "realtps_import"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
realtps_common = { path = "../realtps_common" }
anyhow = "1.0.45"
structopt = "0.3.25"
ethers = "0.6.2"
tokio = { version = "1.5", features = ["macros", "rt-multi-thread", "time"] }
rand = "0.8.4"
serde = "1.0.130"
serde_derive = "1.0.130"
toml = "0.5.8"
futures = "0.3.18"
log = "0.4.14"
env_logger = "0.9.0"

