name: Test
'on': pull_request
jobs:
  checks-and-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the source code
      uses: actions/checkout@v3
      
    - name: Install toolchain
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@stable

    - name: display rust toolchain
      run: rustup show

    - name: Check all features compilation
      run: cargo check --verbose --all-features

    - name: Run all tests
      run: cargo test --all-features
